apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: elephantalpha-staging
resources:
  - namespace.yaml
  - ../../base
  - ingress-staging.yaml
patches:
  - target:
      kind: Deployment
      name: app-elephantalpha
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: app-elephantalpha
      spec:
        template:
          spec:
            containers:
              - name: web
                env:
                  - name: PRIMARY_HOST
                    value: staging.elephantalpha.lol
images:
  - name: registry.144.91.77.245.sslip.io/elephantalpha
    newTag: 169d378afec1b8c28fa318f71072d372e09f6742
