apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elephantalpha-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: elephantalpha
  source:
    repoURL: https://github.com/gateszhangc/elephantalpha.git
    targetRevision: staging
    path: deploy/k8s/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: elephantalpha-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
