apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: elephantalpha
  namespace: argocd
spec:
  description: elephantalpha application managed directly from the application repository
  sourceRepos:
    - https://github.com/gateszhangc/elephantalpha.git
  destinations:
    - namespace: elephantalpha
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
