apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-elephantalpha-www-redirect
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: "https://elephantalpha.lol"
spec:
  ingressClassName: nginx
  rules:
    - host: www.elephantalpha.lol
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-elephantalpha
                port:
                  number: 80
