apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: elephantalpha
resources:
  - namespace.yaml
  - ../../base
  - ingress-live.yaml
  - ingress-www-redirect.yaml
  - ingress-preview.yaml
images:
  - name: registry.144.91.77.245.sslip.io/elephantalpha
    newTag: e7160626332be88fb0559edb1cddf2cc32c67d5b
